### ISSUE TITLE
Undefined role of the 'center' and 'scale' argument

### ISSUE THREAD

**Issue by camhao168** [jianlong-yuan/syncbn-tensorflow#1]
Hi,
Firstly, I really appreciate your work.
However, I see that the 'center' and 'scale' argument do not contribute to operation of 'beta' and 'gamma'. 
Can your please clarify the setting of 'center' and 'scale' in your code?

Thank you

**Comment by jianlong-yuan** [comment]
Sometimes, BN doesn't use gamma. So you do not need create gamma variable. But this code does not use this argument.
