### ISSUE TITLE
Question: tf.nn.batch_normalization vs tf.nn.fused_batch_norm

### ISSUE THREAD

**Issue by sryap** [jianlong-yuan/syncbn-tensorflow#5]
I'm curious why don't you use  `tf.nn.fused_batch_norm` for both training and inference?  Is there a reason to use `tf.nn.batch_normalization` in training and  `tf.nn.fused_batch_norm` in inference?

Thanks!

**Comment by jianlong-yuan** [comment]
i found tf.nn.fused_batch_norm has different result with tf.nn.batch_normalization. For more precision, i use tf.nn.fused_batch_norm

**Comment by sryap** [comment]
Thanks
