### ISSUE TITLE
Error of 'outputs.device[-1]'

### ISSUE THREAD

**Issue by wangq95** [jianlong-yuan/syncbn-tensorflow#7]
Hi, when I use this code, an error occurred at this position:
 
 74       if int(outputs.device[-1])== 0:         
 75         update_moving_mean_op = tf.assign(moving_mean, moving_mean * decay + mean * (1 - decay))
 76         update_moving_var_op  = tf.assign(moving_var,  moving_var  * decay + var  * (1 - decay))
 77         add_model_variable(moving_mean)       
 78         add_model_variable(moving_var)        

the error message is as follows:

  File "/home/wangqiang/cycleGan_make3D/syncbn_tf.py", line 74, in sync_batch_norm
    if int(outputs.device[-1])== 0:
IndexError: string index out of range

Then I print out the 'outputs.devide' and it is NULL, so the index -1 out of the range. Can you help me to solve this problem? Best regards!

**Comment by jianlong-yuan** [comment]
which version of tensorflow?

**Comment by wangq95** [comment]
Hi, I use the Tensorflow 1.3.0 - gpu, should it work in a higher version?

**Comment by jianlong-yuan** [comment]
Yes, i test on tensorflow 1.7

**Comment by wangq95** [comment]
Thank you, I will have a try.

**Comment by wangq95** [comment]
Hi, I have try to update the version of Tf to 1.7.0 with Cuda9 and cudnn 7.0, it still not work because of the same problem above,do I have to do additional operations?

**Comment by wangq95** [comment]
Hi, I think I find the reason of this error, this function must be used in the scripts who run on multi-gpu, thank you for your work, best regards!
